
server:
  port: 7071

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: testGroup
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer